### ISSUE TITLE
vmware serialnumber input sanitation

### ISSUE THREAD

**Issue by TaLoN1x** [bl4ko/netbox-ssot#143] opened 2024-05-06 10:56 UTC
Currently virtual appliances are being created as devices, in fact there is no physical devices and thing runs on a VM instead of physical device. This creates two problems:

- model is inaccurate and virtual appliances should be modeled as VM, not as physical device. The question remains how to detect if appliance is virtual or physical from the APIs
- virtual appliances often have weird and long generated serial numbers, that are not accepted by netbox due to char limit

ERROR   (vc-test): failed to add vmware host virtual-vsan-host.local with error: unexpected status code: 400: {"serial":["Ensure this field has no more than 50 characters."]}

I'd suggest there are 2 things:
1. Ignore malformed serial numbers (if sn is longer than 50 characters, that in real world rarely happens, ignore it in case device reports garbage)
2. Investigate and remodel virtual appliances as part of compute cluster. (affects all currently supported hypervisors)

I will think of the second point for some time in detils

**Comment by bl4ko** [comment] 2024-05-06 11:07
Yeah I aggree with this issue, but the problem is how netbox organizes objects. If you don't map virtual appliances that represent hosts to devices, then you lose useful netbox relation:

- VMs can only be assigned to device (can't be to another vm), so lets say we have host that is virtualized. We add it as an vm but then we can't connect other vms running on this host with it.

**Comment by TaLoN1x** [comment] 2024-05-06 11:20
Virtual appliances are mostly Firewalls, Virtual Storage Devices, Virtual Switches, etc. This would not affect this functionality,  in some cases would even enable the use of abstraction layer for capacity planning.

**Comment by bl4ko** [comment] 2024-05-06 11:27
But you only have `virtual machines` object in netbox to represent virtual appliances. So would it make sense to create firewalls, virtual switches, etc. as `virtual machines`?

**Comment by TaLoN1x** [comment] 2024-05-06 11:36
yes, but currently vsans, vswitches  in vmware are being created as devices.

**Comment by bl4ko** [comment] 2024-05-07 08:02
Would you be able to help me with this issue, e.g. provide some logic of how to implement this, and which devices to map to which virtualization appliances?

**Closed** 2024-11-27 09:13 UTC
Labels: enhancement
